### PR TITLE
Add colorizer italic theme

### PR DESCRIPTION
**Pull request by obgum**
Added a colorizer theme with the italic for keywords

### CODE REVIEW

**Comment by nicollasricas** [comment]
👍

**Comment by EliverLara** [comment]
Why not just add italics to the current colorizer theme?, I mean, I'd like to keep it as simple as possible.

**Comment by nicollasricas** [comment]
I would hate that. It makes sense have an italic colourizer since there's a full theme with an italic variation, now colourizer should have either. But that's your call.

**Comment by EliverLara** [comment]
@nicollasricas  it makes sense what you say, I'm going to merge this, once the data is correct.

**Pull request closed without merging**
